apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: task-app-monitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      monitoring: spring-boot
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s