apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-app
  labels:
    app: task-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: task-app

  template:
    metadata:
      labels:
        app: task-app

    spec:
      containers:
      - name: task-app

        image: taskmanagemntacr.azurecr.io/task-app:v1

        ports:
        - containerPort: 8080

        imagePullPolicy: Always

        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"

          limits:
            cpu: "500m"
            memory: "512Mi"

        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 20

        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
